name: Windows CI
# on: [push, pull_request]
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
